### ISSUE TITLE
Multiple commands on message

### ISSUE THREAD

**Issue by donbubu** [Fireflies/BungeeEssentials#17]
hi,
the rules-check trigger only on time on same regex/pattern.
i have two times the same pattern with two different command but it only execute the first pattern and ignore the second.
i use version BungeeEssentials 2.4.3.

message.yml:

```
....
  - pattern: '([a-zA-Z0-9\-\.]{2})+\.[a-zA-Z]{2}'
    handle: COMMAND
    command: 'warn {{ SENDER }} Keine Internet-Adressen'
  - pattern: '([a-zA-Z0-9\-\.]{2})+\.[a-zA-Z]{2}'
    handle: COMMAND
    command: 'gkick {{ SENDER }} Keine Internet-Adressen'
....
```

**Comment by pantherman594** [comment]
This can be done using aliases. Example:
config.yml:

``` yml
...
aliases:
  - alias: 'kickwarn'
    commands:
      - 'warn {0} Keine Internet-Adressen'
      - 'gkick {0} Keine Internet-Adressen'
...
```

messages.yml:

``` yml
...
  - pattern: '([a-zA-Z0-9\-\.]{2})+\.[a-zA-Z]{2}'
    handle: COMMAND
    command: 'kickwarn {{ SENDER }}'
...
```
